# Site settings
title: Line and Pull
banner: LINE AND PULL
description: Art, Design, Illustration & Photography
email: sue@lineandpull.co.uk
url: http://lineandpull.co.uk
baseurl: ''
port: 3000

twitter_username: sue_jarman
github_username:  lineandpull
tumblr_username: sue@suejarman.co.uk
copyright_owner: Sue Jarman

# Build settings
markdown: kramdown
permalink: pretty

# Collections
collections:
  galleryIllustration:
    output: true
  galleryDesign:
    output: true
